services:
  nginx_web:
    image: nginx:latest
    platform: linux/arm64
    container_name: nginx_web
    networks:
      shared_net:
        ipv4_address: 172.19.5.2
    volumes:
      - ./nginx/www:/usr/share/nginx/html

  # Network monitoring containers
  suricata:
    image: jasonish/suricata
    platform: linux/arm64
    container_name: suricata
    depends_on:
      - nginx_web
    network_mode: "container:nginx_web"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./logs:/var/log/suricata
      - ./suricata/suricata.rules:/etc/suricata/rules/suricata.rules
    command: /usr/bin/suricata -i eth0 -c /etc/suricata/suricata.yaml

  # Attacking containers
  attacker_syn:
    image: debian:bullseye-slim
    container_name: attacker1
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 -S -p 80 -i 1 172.19.5.2; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.3

  attacker_udp:
    image: debian:bullseye-slim
    container_name: attacker2
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 --udp -p 53 -i 1 172.19.5.2; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.4

  attacker_efs:
    image: debian
    platform: linux/arm64
    container_name: attacker_efs
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 --rst --destport 520 -i 1 172.19.5.2; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.5

  attacker_ftp_data:
    image: debian
    platform: linux/arm64
    container_name: attacker_ftp_data
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 --rst --destport 20 -i 1 172.19.5.2; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.6

  # Legitimate containers
  http_client:
    image: alpine
    platform: linux/arm64
    container_name: http_client
    command: sh -c "while true; do wget -qO- http://172.19.5.2/small.html; sleep 2; wget -qO- http://172.19.5.2/medium.html; sleep 2; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.7

  curl_client:
    image: alpine
    platform: linux/arm64
    container_name: curl_client
    command: >
      sh -c "
        apk add --no-cache curl && 
        while true; do
          curl -s http://172.19.5.2
          sleep 2
        done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.8

  # Model deployment containers
  xgboost_model:
    image: python:3.10-slim
    platform: linux/arm64
    container_name: xgboost_model
    volumes:
      - ./models/xgb:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy xgboost && python3 /models/deploy_xgb.py"

  random_forest_model:
    image: python:3.10-slim
    platform: linux/arm64
    container_name: random_forest_model
    volumes:
      - ./models/rf:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_rf.py"

  decision_tree_model:
    image: python:3.10-slim
    platform: linux/arm64
    container_name: decision_tree_model
    volumes:
      - ./models/dt:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_dt.py"

  logistic_regression_model:
    image: python:3.10-slim
    platform: linux/arm64
    container_name: logistic_regression_model
    volumes:
      - ./models/lr:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_lr.py"

  ae_xgboost_model:
    image: armswdev/tensorflow-arm-neoverse
    platform: linux/arm64
    container_name: ae_xgboost_model
    volumes:
      - ./models/ae_xgb:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy xgboost && python3 /models/deploy_aexgb.py"

  cnn_lstm_model:
    image: armswdev/tensorflow-arm-neoverse
    platform: linux/arm64
    container_name: cnn_lstm_model
    volumes:
      - ./models/cnn_lstm:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_cnn_lstm.py"

networks:
  shared_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.5.0/24