services:
  nginx_web:
    image: nginx:latest
    platform: linux/amd64
    container_name: nginx_web
    networks:
      shared_net:
        ipv4_address: 172.19.5.2

  suricata:
    image: jasonish/suricata
    platform: linux/amd64
    container_name: suricata
    depends_on:
      - nginx_web
    network_mode: "container:nginx_web"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./logs:/var/log/suricata
      - ./suricata/suricata.rules:/etc/suricata/rules/suricata.rules
    command: /usr/bin/suricata -i eth0 -c /etc/suricata/suricata.yaml

  attacker1:
    image: debian
    platform: linux/amd64
    container_name: attacker1
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 -S -p 80 172.19.5.2; sleep 1; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.3

  attacker2:
    image: debian
    platform: linux/amd64
    container_name: attacker2
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 --udp -p 80 172.19.5.2; sleep 1; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.4

  attacker3:
    image: python:3.8-slim
    platform: linux/amd64
    container_name: attacker3
    command: sh -c "pip install slowloris && slowloris 172.19.5.2"
    networks:
      shared_net:
        ipv4_address: 172.19.5.5

  xgboost_model:
    image: tensorflow/tensorflow:latest
    platform: linux/amd64
    container_name: xgboost_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.6
    volumes:
      - ./models/xgb:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy xgboost && python3 /models/deploy_xgb.py"

  lr_model:
    image: tensorflow/tensorflow:latest
    platform: linux/amd64
    container_name: lr_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.7
    volumes:
      - ./models/lr:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_lr.py"

  dt_model:
    image: tensorflow/tensorflow:latest
    platform: linux/amd64
    container_name: dt_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.8
    volumes:
      - ./models/dt:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_dt.py"

  rf_model:
    image: tensorflow/tensorflow:latest
    platform: linux/amd64
    container_name: rf_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.9
    volumes:
      - ./models/rf:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_rf.py"

  ae_xgb_model:
    image: armswdev/tensorflow-arm-neoverse
    platform: linux/arm64
    container_name: ae_xgb_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.10
    volumes:
      - ./models/ae_xgb:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy xgboost && python3 /models/deploy_aexgb.py"

  cnn_lstm_model:
    image: armswdev/tensorflow-arm-neoverse
    platform: linux/arm64
    container_name: cnn_lstm_model
    networks:
      shared_net:
        ipv4_address: 172.19.5.11
    volumes:
      - ./models/cnn_lstm:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy && python3 /models/deploy_cnn_lstm.py"

  legit1:
    image: alpine
    platform: linux/amd64
    container_name: legit1
    command: sh -c "while true; do wget -qO- 172.19.5.2; sleep 5; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.12

  legit2:
    image: alpine
    platform: linux/amd64
    container_name: legit2
    command: sh -c "while true; do wget -qO- 172.19.5.2; sleep 5; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.13

networks:
  shared_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.5.0/24