# Base Dockerfile for deep learning models
FROM tensorflow/tensorflow:latest

# Install necessary Python libraries for deep learning models
RUN pip install --no-cache-dir scikit-learn joblib numpy xgboost

# Set the working directory for the models
WORKDIR /models