version: '3.8'

services:
  nginx_web:
    image: nginx:latest
    platform: linux/amd64
    container_name: nginx_web  # Fixed container name
    networks:
      shared_net:
        ipv4_address: 172.19.5.2

  suricata:
    image: jasonish/suricata
    platform: linux/amd64
    depends_on:
      - nginx_web
    network_mode: "container:nginx_web"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./logs:/var/log/suricata
      - ./rules/suricata.rules:/etc/suricata/rules/suricata.rules
    command: /usr/bin/suricata -i eth0 -c /etc/suricata/suricata.yaml

  attacker1:
    image: debian
    platform: linux/amd64
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 -S -p 80 172.19.5.2; sleep 1; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.3

  attacker2:
    image: debian
    platform: linux/amd64
    command: sh -c "apt-get update && apt-get install -y hping3 && while true; do hping3 --icmp 172.19.5.2; sleep 1; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.4

  attacker3:
    image: python:3.8-slim
    platform: linux/amd64
    command: sh -c "pip install slowloris && slowloris 172.19.5.2"
    networks:
      shared_net:
        ipv4_address: 172.19.5.5

  xgboost_model:
    image: tensorflow/tensorflow:latest
    platform: linux/amd64
    networks:
      shared_net:
        ipv4_address: 172.19.5.7
    volumes:
      - ./models/xgb:/models
      - ./logs:/var/log/suricata
    command: sh -c "pip install scikit-learn joblib numpy xgboost && python3 /models/deploy_xgb.py"

  legit1:
    image: alpine
    platform: linux/amd64
    command: sh -c "while true; do wget -qO- 172.19.5.2; sleep 5; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.8

  legit2:
    image: alpine
    platform: linux/amd64
    command: sh -c "while true; do wget -qO- 172.19.5.2; sleep 5; done"
    networks:
      shared_net:
        ipv4_address: 172.19.5.9

networks:
  shared_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.5.0/24