receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'nginx'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8080']
          metrics_path: /metrics
  
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      memory:
      network:
      process:

processors:
  batch:

exporters:
  otlp:
    endpoint: "172.19.5.15:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus, hostmetrics]
      processors: [batch]
      exporters: [otlp]